export default {
  id: "cline",
  priority: 80,
  alias: "cl",
  uiAlias: "cl",
  display: {
    name: "Cline",
    icon: "smart_toy",
    color: "#5B9BD5",
    textIcon: "CL",
    website: "https://cline.bot",
    notice: {
      signupUrl: "https://cline.bot",
    },
  },
  category: "oauth",
  authModes: ["oauth", "apikey"],
  hasOAuth: true,
  passthroughModels: true,
  defaultModel: "deepseek/deepseek-v4-flash",
  transport: {
    baseUrl: "https://api.cline.bot/api/v1/chat/completions",
    headers: {
      "HTTP-Referer": "https://cline.bot",
      "X-Title": "Cline",
    },
    tokenUrl: "https://api.cline.bot/api/v1/auth/token",
    refreshUrl: "https://api.cline.bot/api/v1/auth/refresh",
    auth: {
      combined: true,
      header: "Authorization",
      scheme: "bearer",
      hooks: [
        "clineHeaders",
      ],
    },
  },
  models: [
    { id: "deepseek/deepseek-v4-flash", name: "DeepSeek V4 Flash (Free)" },
    { id: "deepseek/deepseek-v4-pro", name: "DeepSeek V4 Pro" },
    { id: "poolside/laguna-s-2.1:free", name: "Laguna S 2.1 (Free)" },
    { id: "poolside/laguna-xs-2.1:free", name: "Laguna XS 2.1 (Free)" },
    { id: "zai/glm-5.3-flash", name: "GLM 5.3 Flash (Free)" },
    { id: "openrouter/free", name: "OpenRouter Free" },
    { id: "google/gemma-4-31b-it:free", name: "Gemma 4 31B (Free)" },
    { id: "google/gemma-4-26b-a4b-it:free", name: "Gemma 4 26B (Free)" },
    { id: "dots-studio/dots-3-note-preview:free", name: "Dots 3 Note Preview (Free)" },
    { id: "thinkingmachines/inkling:free", name: "Inkling (Free)" },
    { id: "nex-agi/nex-n2.5-mini:free", name: "Nex N2.5 Mini (Free)" },
    { id: "inclusionai/ling-3.0-flash-fin:free", name: "Ling 3.0 Flash Fin (Free)" },
    { id: "deepseek/deepseek-chat", name: "DeepSeek Chat (V3)" },
    { id: "deepseek/deepseek-r1", name: "DeepSeek R1" },
    { id: "cline-pass/glm-5.2", name: "GLM-5.2 (ClinePass)" },
    { id: "cline-pass/deepseek-v4-flash", name: "DeepSeek V4 Flash (ClinePass)" },
    { id: "cline-pass/qwen3.7-max", name: "Qwen3.7 Max (ClinePass)" },
    { id: "anthropic/claude-sonnet-4.6", name: "Claude Sonnet 4.6" },
    { id: "anthropic/claude-opus-4.7", name: "Claude Opus 4.7" },
    { id: "anthropic/claude-opus-4.6", name: "Claude Opus 4.6" },
    { id: "openai/gpt-5.4", name: "GPT-5.4" },
    { id: "openai/gpt-5.3-codex", name: "GPT-5.3 Codex" },
    { id: "google/gemini-3.1-pro-preview", name: "Gemini 3.1 Pro Preview" },
    { id: "google/gemini-3.1-flash-lite-preview", name: "Gemini 3.1 Flash Lite Preview" },
    { id: "kwaipilot/kat-coder-pro", name: "KAT Coder Pro" },
  ],
  oauth: {
    clientId: "client_01K3A541FN8TA3EPPHTD2325AR",
    appBaseUrl: "https://app.cline.bot",
    apiBaseUrl: "https://api.cline.bot",
    deviceCodeUrl: "https://api.workos.com/user_management/authorize/device",
    tokenUrl: "https://api.workos.com/user_management/authenticate",
    registerUrl: "https://api.cline.bot/api/v1/auth/register",
    refreshUrl: "https://api.cline.bot/api/v1/auth/refresh",
    authorizeUrl: "https://api.cline.bot/api/v1/auth/authorize",
    tokenExchangeUrl: "https://api.cline.bot/api/v1/auth/token",
  },
  thinkingConfig: {
    options: ["auto", "on", "off"],
    defaultMode: "auto",
  },
};

